name: simple_autocomplete_formfield
description: A Flutter widget that wraps a TextFormField and assists with autocomplete functionality.
version: 0.2.8
homepage: https://github.com/jifalops/simple_autocomplete_formfield

dependencies:
  flutter:
    sdk: flutter
  textfield_state: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.1.2 <2.0.0"