name: efficient_autocomplete_formfield
description: Improve TextFormFields with efficient autocomplete features.
version: 0.3.1
homepage: https://github.com/yurtemre7/simple_autocomplete_formfield

dependencies:
  flutter:
    sdk: flutter
  textfield_state: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

environment:
  sdk: ">=2.17.0 <3.0.0"